Repository Meghsham15/Book-Shelf-2.0, pull requests merged in 2022-10, with the labels that each got.

#17 Update Books.js
  Books.js
Labels: hacktoberfest, hactoberfest-accepted, hactober-accepted, hacktoberfest-accepted, hacktober-accepted

#18 Update Books.js
  Books.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#19 add new book
  Books.js
Labels: hacktoberfest, hactober-accepted, hacktoberfest-accepted
