Repository Meghsham15/Book-Shelf-2.0, pull requests merged in 2022-09, with the labels that each got.

#1 Update Books.js
  Books.js
Labels: hacktoberfest

#2 added id 50
  Books.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#5 updated
  Books.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#4 added book no 5
  Books.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#6 Update Books.js
  Books.js
Labels: hacktoberfest, hactober-accepted, hacktoberfest-accepted, hacktober-accepted

#7 Added book
  Books.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#8 id 6 added
  Books.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#9 added 19
  Books.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#10 id 8 added
  Books.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#11 id 20 added
  Books.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#12 id 22 added
  Books.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#13 add my id
  Books.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#14 Added new name
  Books.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#15 Update Books.js
  Books.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#16 add my info
  Books.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted
